version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: springdb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpass
    ports:
      - "5432:5432"   # <-- port standard, ou remplace par un port libre
    volumes:
      - pgdata:/var/lib/postgresql/data

  tomcat:
    build: .
    container_name: spring-tomcat
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin@admin.com
    depends_on:
      - db
volumes:
  pgdata: